// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XIVRepo.EntityFramework;

namespace XIVRepo.EntityFramework.Migrations
{
    [DbContext(typeof(XivRepoDbContext))]
    [Migration("20210908064004_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.Property<Guid>("AccountsWithRoleAccountId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RolesRoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("AccountsWithRoleAccountId", "RolesRoleId");

                    b.HasIndex("RolesRoleId");

                    b.ToTable("AccountRole");
                });

            modelBuilder.Entity("XIVRepo.Core.Models.Accounts.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AccountId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("XIVRepo.Core.Models.Accounts.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.HasOne("XIVRepo.Core.Models.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountsWithRoleAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XIVRepo.Core.Models.Accounts.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
